server:
  port: 8086
spring:
  rabbitmq:
    host: 192.168.174.136 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
hm:
  swagger:
    title: 支付管理
    description: 支付管理
    package: com.hmall.pay.controller
  db:
    database: hm-pay
