server:
  port: 8081
hm:
  swagger:
    title: 商品服务接口文档
    package: com.hmall.item.controller
  db:
    database: hm-item
spring:
  rabbitmq:
    host: 192.168.174.136 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
